"""empty message

Revision ID: 558ad1c63bd0
Revises: e423a12d51e8
Create Date: 2021-04-30 23:49:36.717987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558ad1c63bd0'
down_revision = 'e423a12d51e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cargo', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('setor', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'setor')
    op.drop_column('users', 'cargo')
    # ### end Alembic commands ###
